CREATE DATABASE IF NOT EXISTS todo
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE todo;

CREATE TABLE IF NOT EXISTS tache (
  id_tache INT AUTO_INCREMENT PRIMARY KEY,
  titre VARCHAR(100) NOT NULL,
  description TEXT,
  fait BOOLEAN NOT NULL DEFAULT 0,
  date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
